SET(FILE_PATH ${CMAKE_CURRENT_LIST_DIR})

FUNCTION (GET_ASM VAR)
    IF (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        SET(${VAR} "${FILE_PATH}/gcc.S.in" PARENT_SCOPE)
#    ELSEIF (CMAKE_CXX_COMPILER_ID STREQUAL "Clang") # TODO
#    ELSEIF (CMAKE_CXX_COMPILER_ID STREQUAL "Intel") # TODO
#    ELSEIF (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")  # TODO
    ELSEIF()
        MESSAGE(FATAL_ERROR "INJECT_RESOURCES: COMPILER ${CMAKE_CXX_COMPILER_ID} IS NOT SUPPORTED")
    ENDIF()
ENDFUNCTION()