SET(FILE_PATH ${CMAKE_CURRENT_LIST_DIR})

FUNCTION(__RES_INJ_CHECK_GCC_STYLE)
    IF (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR
            CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        SET(INJECTOR::GCC_STYLE TRUE PARENT_SCOPE)
    ENDIF()
ENDFUNCTION()

FUNCTION(__RES_INJ_CHECK_APPLE_CLANG)
    IF (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        SET(INJECTOR::APPLE_CLANG TRUE PARENT_SCOPE)
    ENDIF()
ENDFUNCTION()

FUNCTION (__RES_INJ_GET_ASM VAR)
    __RES_INJ_CHECK_GCC_STYLE()
    __RES_INJ_CHECK_APPLE_CLANG()

    IF (DEFINED INJECTOR::GCC_STYLE)
        SET(${VAR} "${FILE_PATH}/gcc.S.in" PARENT_SCOPE)
    ELSEIF (DEFINED INJECTOR::APPLE_CLANG)
        SET(${VAR} "${FILE_PATH}/apple-clang.S.in" PARENT_SCOPE)
#    ELSEIF (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")  # TODO
    ELSEIF()
        MESSAGE(FATAL_ERROR "INJECT_RESOURCES: COMPILER ${CMAKE_CXX_COMPILER_ID} IS NOT SUPPORTED")
    ENDIF()
ENDFUNCTION()