INCLUDE(${CMAKE_CURRENT_LIST_DIR}/TargetUtils.cmake)

MACRO(__RES_INJ_SHOW_CODE CODE)
    LIST(JOIN ${CODE} ";" ___THE_CODE)
    MESSAGE("CODE:\n${___THE_CODE}")
ENDMACRO()

MACRO(__RES_INJ_NEW_CODE NAME TEXT)
    SET(${NAME} "${TEXT}")
ENDMACRO()

MACRO(__RES_INJ_APPEND_CODE CODE ADDITIVE)
    LIST(APPEND ${CODE} "${${ADDITIVE}}")
ENDMACRO()

MACRO(__RES_INJ_APPEND_COMMA_SEP LST ELEM)
    IF (NOT ${LST})
        SET(${LST} "${${ELEM}}")
    ELSE()
        SET(${LST} "${${LST}},${${ELEM}}")
    ENDIF()
ENDMACRO()

MACRO(__RES_INJ_UPDATE_CODE_VAR VAR VALUE)
    ## SOURCE_PREFIX MUST BE DEFINED !
    ## TARGET        MUST BE DEFINED !

    SET(___VAR_NAME ${SOURCE_PREFIX}_${VAR})
    __RES_INJ_TARGET_REMOVE_DEFINITION(${TARGET} ${___VAR_NAME})
    STRING(REPLACE "\n" " " ___NEW_TEXT "${${VALUE}}")
    LIST(JOIN ___NEW_TEXT "\\\;" ___NEW_TEXT)
    TARGET_COMPILE_DEFINITIONS(${TARGET} PRIVATE ${___VAR_NAME}=${___NEW_TEXT})
ENDMACRO()
